version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingfederate-admin:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-aws-s3-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED
      
      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate
      
      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - PF_CLUSTER_NAME=COMPOSE_PF_CLUSTER

      # AWS S3 Bucket details
      - DISCOVERY_S3_LOCATION=${DISCOVERY_S3_LOCATION}
      - DISCOVERY_S3_ACCESS_KEY=${DISCOVERY_S3_ACCESS_KEY}
      - DISCOVERY_S3_SECRET_KEY=${DISCOVERY_S3_SECRET_KEY}
    env_file:
      - ~/.pingidentity/devops  
    ports:
      - "9999:9999"
    networks:
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-aws-s3-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED
      
      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate     
      
      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - PF_CLUSTER_NAME=COMPOSE_PF_CLUSTER

      # AWS S3 Bucket details
      - DISCOVERY_S3_LOCATION=${DISCOVERY_S3_LOCATION}
      - DISCOVERY_S3_ACCESS_KEY=${DISCOVERY_S3_ACCESS_KEY}
      - DISCOVERY_S3_SECRET_KEY=${DISCOVERY_S3_SECRET_KEY}
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 9031-9041:9031
    networks:
      - pingnet

networks:
  pingnet:
    ipam:
      config:
        - subnet: 169.254.1.0/24