version: "3.6"

services:
  pingdirectory:
    image: pingidentity/pingdirectory${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - TOPOLOGY_SIZE=2
      - TOPOLOGY_PREFIX=02-replicated-pair_pingdirectory_
    networks:
      - pingnet
    ports:
      - 1389-1399:389
      - 1636-1646:636
      - 1443-1453:443
      
  pingdataconsole:
    image: pingidentity/pingdataconsole
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet
                    
networks:
    pingnet:
