version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingaccess:
    image: pingidentity/pingaccess:edge
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u administrator:2FederateM0re -H \"X-XSRF-Header: PingAccess\" -k https://localhost:9000/pa-admin-api/v3/sites | jq -e '.items[0].name' "]
      interval: 10s
      timeout: 3s    
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pa-clustering/pingaccess
      - PING_IDENTITY_ACCEPT_EULA=YES
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - PA_CONSOLE_HOST=pingaccess
    env_file:
     - ~/.pingidentity/devops    
    # volumes:
      # - ${HOME}/projects/pingidentity-server-profiles/pa-clustering/pingaccess:/opt/in
      #- ${HOME}/<PATH_TO_LOCAL_REPO>/pa-clustering/pingaccess:/opt/in
    ports:
      - 9000:9000
      - 9090:9090
    networks:
      - pingnet
    cap_add:
      - NET_ADMIN

  pingaccess-engine:
    image: pingidentity/pingaccess:edge
    command: wait-for pingaccess:9000 -t 420 -- entrypoint.sh start-server
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pa-clustering/pingaccess
      - PING_IDENTITY_ACCEPT_EULA=YES
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - PA_CONSOLE_HOST=pingaccess
    env_file:
     - ~/.pingidentity/devops      
    # volumes:
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/pa-clustering/pingaccess:/opt/in
    #  - ${HOME}/<PATH_TO_LOCAL_REPO>/pa-clustering/pingaccess:/opt/in
    ports:
      - 3000-3010:3000
    networks:
      - pingnet              
networks:
    pingnet: