apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: pdg-pap-integration/pingdatagovernancepap
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  REST_API_HOSTNAME: localhost
kind: ConfigMap
metadata:
  labels:
    role: pingdatagovernancepap
  name: pingdatagovernancepap-environment-variables
