kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# requirements beyond 01-standalone for replication: 
#   1. additional environment variables must be passed - by replacing the configmap
#   2. number of replicas is increased - patch
# 
#   additionally, we create a storage class and mount volumes to prepare for disasters. 

resources:
- ../01-standalone/pingdataconsole
- ../01-standalone/pingdirectory
- storage.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: replace
  env: env_vars.pingdirectory

patches:
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/replicas
      value: 2
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value: [{"name":"out-dir","mountPath":"/opt/out"}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/volumeClaimTemplates
      value: [{"metadata":{"name":"out-dir"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"pingdirectory-gp2"}}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value: [{"name":"out-dir","persistentVolumeClaim":{"claimName":"out-dir"}}]
