kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  role: pingaccess

resources:
- pingaccess.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-environment-variables
  env: env_vars