kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingAccess getting started demo
#-
#-                +---------------+
#-                |   PingAccess  |
#-                +---------------+
#-
#- Setup a port-forward on port 9000 to the pingaccess service.
#-
#-    kubectl port-forward service/pingaccess 9000
#-
#- To access PingAccess Console.
#- 
#-    https://localhost:9000/
#-    
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

resources:
- pingaccess.yaml
- configmap.yaml