kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- Setup a port-forward on port 9999 to the pingfederate service.
#-
#-    kubectl port-forward service/pingfederate 9031 9999
#-
#- To access PingFederate Console
#- 
#-    https://localhost:9999/pingfederate/app
#-    
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

resources:
- pingfederate.yaml
- configmap.yaml
