apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    role: pingaccess
  name: pingaccess
spec:
  rules:
  # example pingaccess-admin-yourname.ping-devops.com
  - host: pingaccess-admin-${PING_IDENTITY_DEVOPS_DNS_ZONE}
    http:
      paths:
      - backend:
          serviceName: pingaccess
          servicePort: 9000
        path: /
  - host: pingaccess-${PING_IDENTITY_DEVOPS_DNS_ZONE}
    http:
      paths:
      - backend:
          serviceName: pingaccess
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - pingaccess-admin-${PING_IDENTITY_DEVOPS_DNS_ZONE}
    secretName: tls-secret
  - hosts:
    - pingaccess-${PING_IDENTITY_DEVOPS_DNS_ZONE}
    secretName: tls-secret