version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- To access PingFederate Console
#- 
#-    https://localhost:9999/pingfederate/app
#-    
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
    env_file:
      - ~/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
                    
networks:
    pingnet:
