version: "2.4"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingfederate-admin:
    image: pingidentity/pingfederate:edge
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-dns-ping-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED

      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate

      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - CLUSTER_NAME=COMPOSE_PF_CLUSTER
      - DNS_QUERY_LOCATION=pingfederate-admin
      - DNS_RECORD_TYPE=A
      - PF_LDAP_USERNAME="Administrator"
      - PF_LDAP_PASSWORD="2FederateM0re"
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - pingfederate-admin-out:/opt/out

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-dns-ping-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED

      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate

      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - CLUSTER_NAME=COMPOSE_PF_CLUSTER
      - DNS_QUERY_LOCATION=pingfederate-admin
      - DNS_RECORD_TYPE=A
      - PF_LDAP_USERNAME="Administrator"
      - PF_LDAP_PASSWORD="2FederateM0re"
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - 9031-9051:9031
    networks:
      - pingnet

networks:
  pingnet:
    ipam:
      config:
        - subnet: 169.254.1.0/24

volumes:
  pingfederate-admin-out:
