version: "3.1"

services:
  pingfederate-admin:
    image: pingidentity/pingfederate:edge
    environment:
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-compose-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED
      
      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate
      
      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - PF_CLUSTER_NAME=COMPOSE_PF_CLUSTER

      # AWS S3 Bucket details
      - DISCOVERY_S3_LOCATION=
      - DISCOVERY_S3_ACCESS_KEY=
      - DISCOVERY_S3_SECRET_KEY=
    env_file:
      - ~/.pingidentity/devops  
    ports:
      - 9999:9999
    networks:
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: ["sh", "-c", "wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server"]
    environment:
      # Server Profile - Clustering
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-compose-clustering/pingfederate
      - SERVER_PROFILE_PARENT=GETTING_STARTED
      
      # Getting Started Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate     
      
      # PingFederate Settings
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - CLUSTER_BIND_ADDRESS=COMPOSE_PF_CLUSTER
     
      # AWS S3 Bucket details
      - DISCOVERY_S3_LOCATION=
      - DISCOVERY_S3_ACCESS_KEY=
      - DISCOVERY_S3_SECRET_KEY=
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 9031-9041:9031
    networks:
      - pingnet

networks:
  pingnet:
    ipam:
      config:
        - subnet: 169.254.1.0/24