version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingCentral getting started demo
#-
#-                +---------------+
#-                |  PingCentral  |
#-                +---------------+
#-
#- To access PingCentral Console
#- 
#-    https://localhost:9022/
#-    
#-    Username: administrator
#-    Password: 2Federate
#-------------------------------------------------------------------------------------

services:
  pingcentral:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY:-docker.io/pingidentity}/pingcentral:${PING_IDENTITY_DEVOPS_TAG:-edge}
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9022:9022"
    networks:
      - pingnet
    volumes:
      - pingcentral-out:/opt/out
networks:
  pingnet:

volumes:
  pingcentral-out:
